spring:
  datasource:

    url: jdbc:mysql://bc8ha8qre3z8.ap-south-2.psdb.cloud:3306/projecthub
    username: s0v7gydg3ej7
    password: pscale_pw_yC4EHkGfTYuAvZsR48Tb7XT1Vz63VnpRUX8Zi9M77cE
    #        url: jdbc:mysql://db4free.net:3306/projecthub
    #        username: projecthub
    #        password: projecthub
    #    url: jdbc:postgresql://localhost:5432/projectHub
    #    username: postgres
    #    password: root
    #    url: jdbc:postgresql://ec2-35-169-119-56.compute-1.amazonaws.com:5432/d3jsec9cdc1p5k?sslmode=require
    #    username: tvwsvvmcieeyyo
    #    password: 72fb347b09c2312149ae23aa32861c0e33b4a7398c631faefeb799741d9cf443
    hikari:
      maximum-pool-size: 10


    #    url: jdbc:postgresql://${RDS_HOST}:${RDS_PORT}/${RDS_DB_NAME}?sslmode=require
    #    username: ${RDS_USERNAME}
    #    password: ${RDS_PASSWORD}

    #     url: jdbc:postgresql://localhost:5432/projectHub
    #     username: postgres
    #     password: root

    #maximum pool size #https://stackoverflow.com/a/68270053


  jpa:
    properties:
      hibernate: #        dialect: org.hibernate.dialect.PostgresPlusDialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: avinashvijayvargiya324@gmail.com
    password: ${PASSWORD}

    # Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          # TLS , port 587
          starttls:
            enable: true